apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: microservices-chassis
spec:
  version: 7.9.1
  nodeSets:
  - name: default
    count: 2
    config:
      node.master: true
      node.data: true
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      xpack.security.enabled: false
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
    podTemplate:
      metadata:
        labels:        
          app: elasticsearch
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          image: docker-registry:4000/docker.elastic.co/elasticsearch/elasticsearch:7.9.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
              memory: 1Gi 
            limits:
              cpu: 15
              memory: 17Gi
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms16g -Xmx16g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
        - name: http
          port: 9200
          protocol: TCP
          targetPort: 9200
          # nodePort: 31589
    tls:
      selfSignedCertificate:
        disabled: true