apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/u01/data/elasticsearch_storage"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-2
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/u01/data/elasticsearch_storage"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-3
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/u01/data/elasticsearch_storage"

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: elasticsearch-data-4
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete  
#   hostPath:
#     path: "/u01/data/elasticsearch_storage"