apiVersion: v1
kind: Service
metadata:
  name: microchassis-cgw
spec:
  clusterIP: None
  selector:
    service-layer: microchassis-cgw
  ports:
    - port: 13003
      targetPort: 13003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-cgw
  labels:
    app: microchassis-cgw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microchassis-cgw
  template:
    metadata:
      labels:
        app: microchassis-cgw
        service-layer: microchassis-cgw
    spec:
      nodeName: vocs40nfvi05
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx2G", "-jar",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=cgw",
            # general
                 "-DNUMBER_OF_CPU=2",
                 "-DserviceType=inner3",
                 "-Dname=cgw",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 3Gi
              cpu: 2
  strategy:
    type: Recreate