apiVersion: v1
kind: Service
metadata:
  name: microchassis-chp
spec:
  clusterIP: None
  selector:
    service-layer: microchassis-chp
  ports:
    - port: 13002
      targetPort: 13002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-chp
  labels:
    app: microchassis-chp
spec:
  replicas: 9
  selector:
    matchLabels:
      app: microchassis-chp
  template:
    metadata:
      labels:
        app: microchassis-chp
        service-layer: microchassis-chp
    spec:
      nodeName: vocs40nfvi02
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx2G", "-jar",
            # server config
                 "-DsPort=13002",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=chp-gy",
            # general
                 "-DNUMBER_OF_CPU=2",
                 "-DserviceType=inner2",
                 "-Dname=chp",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2Gi
              cpu: 2
  strategy:
    type: Recreate