apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
  namespace: microservices-chassis
data:
  span-storage-type: elasticsearch
  collector: |
    log-level: info
    es:
      num-shards: 3
      num-replicas: 1
      # -------------------------
      # bulk.actions: 1000
      bulk.flush-interval: 200ms
      bulk.size: 5000000          
      bulk.workers: 10
      server-urls: http://172.20.3.72:9200
    collector:
      num-workers: 100
      queue-size: 5000
  query: |
    log-level: info
    es:
      server-urls: http://172.20.3.72:9200
  # agent: |
  #   collector:
  #     host-port: "jaeger-collector:14267"