# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: admin-user
#   namespace: microservices-chassis
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: admin-user
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: admin-user
#   namespace: microservices-chassis

apiVersion: v1
kind: ServiceAccount
metadata:
  name: microchassis
  namespace: microservices-chassis
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microchassis-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microchassis-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microchassis-read
subjects:
- kind: ServiceAccount
  name: microchassis
  namespace: microservices-chassis