##################################################################################################
# Server service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    service: service-a
  namespace: microservices-chassis
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31780
    - name: http
      protocol: TCP
      port: 8094
      targetPort: 8094
      nodePort: 31796
---

##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    version: v1
  namespace: microservices-chassis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: v1
  template:
    metadata:
      labels:
        app: service-a
        version: v1
    spec:
      nodeName: "vocs40nfvi02"
      serviceAccountName: microchassis
      containers:
      - name: service-a
        image: docker-registry:4000/microchassis:v1
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "source /app/bin/init-env-for-logging.sh &&
                      java -Dlog4j.configurationFile=./src/main/resources/etc/log4j/log4j2.xml
                      -cp microchassis-tracing/target/microchassis-tracing.jar:microchassis-tracing/target/dependencies/*
                      com.viettel.vocs.microchassis.tracing.example.ServiceA" ]
        ports:
          - name: http2
            containerPort: 8080
          - name: http
            containerPort: 8094
        env:
          # - name: JAEGER_REPORTER_LOG_SPANS
          #   value: "true"
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-production-collector.microservices-chassis.svc:14268/api/traces"
          - name: JAEGER_REPORTER_FLUSH_INTERVAL
            value: "100"
          - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
            value: "2000"
          # - name: JAEGER_AGENT_HOST
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: status.hostIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"
        volumeMounts:
          - name: log-storage
            mountPath: /u01/data/log-storage
          - name: init-env-for-logging
            mountPath: "/app/bin/init-env-for-logging.sh"
            subPath: "init-env-for-logging.sh"
            readOnly: true
      volumes:
        - name: log-storage
          hostPath:
            path: /u01/data/log-storage
        - name: init-env-for-logging
          configMap:
            name: init-env-for-logging