apiVersion: v1
kind: Service
metadata:
  name: microchassis-cgw
spec:
  clusterIP: None
  selector:
    service-layer: microchassis-cgw
  ports:
    - port: 13003
      targetPort: 13003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-cgw-2x
  labels:
    app: microchassis-cgw-2x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-cgw-2x
  template:
    metadata:
      labels:
        app: microchassis-cgw-2x
        service-layer: microchassis-cgw
    spec:
      nodeName: vocs40nfvi05
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx3G", "-jar",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=cgw",
            # general
                 "-DNUMBER_OF_CPU=4",
                 "-DserviceType=inner3",
                 "-Dname=cgw",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 3Gi
              cpu: 4
            limits:
              memory: 4Gi
              cpu: 4
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-cgw-3x
  labels:
    app: microchassis-cgw-3x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-cgw-3x
  template:
    metadata:
      labels:
        app: microchassis-cgw-3x
        service-layer: microchassis-cgw
    spec:
      nodeName: vocs40nfvi05
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx4G", "-jar",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=cgw",
            # general
                 "-DNUMBER_OF_CPU=6",
                 "-DserviceType=inner3",
                 "-Dname=cgw",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 5Gi
              cpu: 6
            limits:
              memory: 6Gi
              cpu: 6
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-cgw-4x
  labels:
    app: microchassis-cgw-4x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-cgw-4x
  template:
    metadata:
      labels:
        app: microchassis-cgw-4x
        service-layer: microchassis-cgw
    spec:
      nodeName: vocs40nfvi05
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx6G", "-jar",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=cgw",
            # general
                 "-DNUMBER_OF_CPU=8",
                 "-DserviceType=inner3",
                 "-Dname=cgw",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 6Gi
              cpu: 8
            limits:
              memory: 8Gi
              cpu: 8
  strategy:
    type: Recreate