apiVersion: v1
kind: Service
metadata:
  name: microchassis-chp
spec:
  clusterIP: None
  selector:
    service-layer: microchassis-chp
  ports:
    - port: 13002
      targetPort: 13002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-chp-2x
  labels:
    app: microchassis-chp-2x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-chp-2x
  template:
    metadata:
      labels:
        app: microchassis-chp-2x
        service-layer: microchassis-chp
    spec:
      nodeName: vocs40nfvi02
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx3G", "-jar",
            # server config
                 "-DsPort=13002",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=chp-gy",
            # general
                 "-DNUMBER_OF_CPU=4",
                 "-DserviceType=inner2",
                 "-Dname=chp",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 3Gi
              cpu: 4
            limits:
              memory: 4Gi
              cpu: 4
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-chp-3x
  labels:
    app: microchassis-chp-3x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-chp-3x
  template:
    metadata:
      labels:
        app: microchassis-chp-3x
        service-layer: microchassis-chp
    spec:
      nodeName: vocs40nfvi02
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx4G", "-jar",
            # server config
                 "-DsPort=13002",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=chp-gy",
            # general
                 "-DNUMBER_OF_CPU=6",
                 "-DserviceType=inner2",
                 "-Dname=chp",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 5Gi
              cpu: 6
            limits:
              memory: 6Gi
              cpu: 6
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-chp-4x
  labels:
    app: microchassis-chp-4x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microchassis-chp-4x
  template:
    metadata:
      labels:
        app: microchassis-chp-4x
        service-layer: microchassis-chp
    spec:
      nodeName: vocs40nfvi02
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx6G", "-jar",
            # server config
                 "-DsPort=13002",
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=chp-gy",
            # general
                 "-DNUMBER_OF_CPU=8",
                 "-DserviceType=inner2",
                 "-Dname=chp",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar" ]
          resources:
            requests:
              memory: 6Gi
              cpu: 8
            limits:
              memory: 8Gi
              cpu: 8
  strategy:
    type: Recreate