apiVersion: v1
kind: Service
metadata:
  name: microchassis-abm
spec:
  clusterIP: None
  selector:
    service-layer: microchassis-abm
  ports:
    - port: 13001
      targetPort: 13001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-abm-2x
  labels:
    app: microchassis-abm-2x
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microchassis-abm-2x
  template:
    metadata:
      labels:
        app: microchassis-abm-2x
        service-layer: microchassis-abm
    spec:
      nodeName: vocs40db03
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx2G", "-jar",
            # server config
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=abm",
            # general
                 "-DNUMBER_OF_CPU=2",
                 "-DserviceType=inner1",
                 "-Dname=abm",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar"]
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 3Gi
              cpu: 2
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-abm-3x
  labels:
    app: microchassis-abm-3x
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microchassis-abm-3x
  template:
    metadata:
      labels:
        app: microchassis-abm-3x
        service-layer: microchassis-abm
    spec:
      nodeName: vocs40db03
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx3G", "-jar",
            # server config
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=abm",
            # general
                 "-DNUMBER_OF_CPU=3",
                 "-DserviceType=inner1",
                 "-Dname=abm",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar"]
          resources:
            requests:
              memory: 3Gi
              cpu: 3
            limits:
              memory: 4.5Gi
              cpu: 3
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microchassis-abm-4x
  labels:
    app: microchassis-abm-4x
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microchassis-abm-4x
  template:
    metadata:
      labels:
        app: microchassis-abm-4x
        service-layer: microchassis-abm
    spec:
      nodeName: vocs40db03
      containers:
        - name: main
          image: docker-registry:4000/tiennn18/microchassis-microservice:4.2
          imagePullPolicy: Always
          env:
            - name: VNF_INSTANCE_NAME # deployment name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DNS_NAME # deployment name = service name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java"]
          args: ["-Xmx4G", "-jar",
            # server config
            # client config
                 "-DclientMode=async",
            # mesh config
                 "-DVDU_NAME=abm",
            # general
                 "-DNUMBER_OF_CPU=4",
                 "-DserviceType=inner1",
                 "-Dname=abm",
                 "-DintervalStatistic=1000", "-Dlog4j.configurationFile=/mesh/mesh-log4j2.xml",
                 "/mesh/microchassis-mesh-jar-with-dependencies.jar"]
          resources:
            requests:
              memory: 4Gi
              cpu: 4
            limits:
              memory: 6Gi
              cpu: 4
  strategy:
    type: Recreate