clients:
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: client_update
    host: csde-abm
    maxRetryConnect: 5
    pingIntervalMs: 5000
    port: 9194
    sendTimeoutMs: 5000
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: client_query
    host: csde-abm
    maxRetryConnect: 5
    pingIntervalMs: 5000
    port: 9194
    sendTimeoutMs: 5000
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: client_notify
    host: csde-cgw
    maxRetryConnect: 5
    pingIntervalMs: 5000
    port: 9209
    sendTimeoutMs: 5000
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: client_mano
    host: csde-mano
    maxRetryConnect: 5
    pingIntervalMs: 5000
    port: 9000
    sendTimeoutMs: 5000
servers:
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: pcf-tcp
    port: 9000
  - channelConfiguration:
      backLog: 1024
      epoll: true
      fastFlush: true
      maxChannelWritableMs: 5000
      maxDecode: 200
      numWorkerThread: 1
      parkWritableNano: 5000
      pooledByteBuffer: true
      preferDirect: true
      timeoutConnectMs: 10000
    id: pcf-http
    port: 8000
    